# Generated by Django 4.2.2 on 2024-05-29 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Default Project Name', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='program_language',
            field=models.CharField(default='default lang name', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
