# Generated by Django 4.2.2 on 2024-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('c', 'C')], max_length=50),
        ),
    ]
