# Generated by Django 4.2.2 on 2024-06-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0002_codesnippet_delete_codebox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='Project',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
