# Generated by Django 4.2.2 on 2024-06-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0003_rename_project_codesnippet_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
