# Generated by Django 4.2.2 on 2024-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0005_alter_codesnippet_project_coderecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coderecord',
            old_name='fixed_code',
            new_name='output',
        ),
        migrations.AddField(
            model_name='coderecord',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
