# Generated by Django 4.2.2 on 2024-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0006_rename_fixed_code_coderecord_output_coderecord_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderecord',
            name='feedback_all',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coderecord',
            name='feedback_only_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coderecord',
            name='feedback_only_word',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coderecord',
            name='token_input',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coderecord',
            name='token_respawn',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
