# Generated by Django 4.2.2 on 2024-07-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0007_coderecord_feedback_all_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coderecord',
            old_name='feedback_only_word',
            new_name='feedback_without_code',
        ),
    ]
