# Generated by Django 4.2.2 on 2024-11-13 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0008_rename_feedback_only_word_coderecord_feedback_without_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderecord',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coderecord',
            name='token_input',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coderecord',
            name='token_respawn',
            field=models.SmallIntegerField(default=0),
        ),
    ]
