# Generated by Django 4.2.2 on 2024-11-13 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0009_coderecord_name_alter_coderecord_token_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderecord',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
