# Generated by Django 4.2.2 on 2024-11-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0012_alter_coderecord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coderecord',
            name='name',
        ),
    ]
