# Generated by Django 4.2.2 on 2024-11-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0014_rename_coderecord_coderecordafterdebug'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
