# Generated by Django 4.2.2 on 2024-11-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0015_codesnippet_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='title',
            new_name='file_name',
        ),
    ]
