# Generated by Django 4.2.2 on 2024-12-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_project_language'),
        ('system_main', '0017_debugrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskAIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_message', models.TextField(blank=True, null=True)),
                ('user_message', models.TextField(blank=True, null=True)),
                ('AI_answer', models.TextField(blank=True, null=True)),
                ('token_input', models.SmallIntegerField(default=0)),
                ('token_respawn', models.SmallIntegerField(default=0)),
                ('token_total', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ManyToManyField(blank=True, to='system_main.codesnippet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.project')),
            ],
        ),
        migrations.AddField(
            model_name='debugrecord',
            name='main_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CodeRecordAfterDebug',
        ),
    ]
