# Generated by Django 4.2.2 on 2024-12-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0018_askairecord_debugrecord_main_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugrecord',
            name='main_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_file_debug_records', to='system_main.codesnippet'),
        ),
    ]
