# Generated by Django 4.2.2 on 2024-12-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0019_alter_debugrecord_main_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debugrecord',
            old_name='created_at',
            new_name='formatted_created_at',
        ),
    ]
