# Generated by Django 4.2.2 on 2024-12-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_main', '0020_rename_created_at_debugrecord_formatted_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debugrecord',
            old_name='formatted_created_at',
            new_name='created_at',
        ),
    ]
